/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import config.koneksi;
import dao.DAO_service;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import model.model_service;
import service.service_service;
import tableModel.table_service;

/**
 *
 * @author SyafiqUbai
 */
public class dashboard extends javax.swing.JPanel {

    /**
     * Creates new form dashboard
     */
    private java.sql.Connection conn;
    
    private service_service servis = new DAO_service();
    private table_service tblModel = new table_service();
    
    public dashboard() {
        initComponents();
        conn = koneksi.getConnection();
        tbl_data.setModel(tblModel);
        loadData();
        hitungJumlahDataBarang();
        hitungJumlahDataMenipis();
        hitungJumlahKasir();
        hitungJumlahMekanik();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn = new javax.swing.JPanel();
        roundPanel1 = new roundpanel.RoundPanel();
        lb_kasir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        jLabel4 = new javax.swing.JLabel();
        roundPanel3 = new roundpanel.RoundPanel();
        lb_mekanik = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        roundPanel4 = new roundpanel.RoundPanel();
        lb_stok = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        roundPanel5 = new roundpanel.RoundPanel();
        lb_stokMenipis = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        pn.setBackground(new java.awt.Color(255, 255, 255));

        roundPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lb_kasir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_kasir.setForeground(new java.awt.Color(255, 255, 255));
        lb_kasir.setText("999");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clerk.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KASIR");

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(lb_kasir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30))))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lb_kasir))
                .addGap(15, 15, 15))
        );

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin111.setViewportView(tbl_data);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setText("Riwayat Data Service");

        roundPanel3.setBackground(new java.awt.Color(0, 153, 153));

        lb_mekanik.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_mekanik.setForeground(new java.awt.Color(255, 255, 255));
        lb_mekanik.setText("999");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/automobile-with-wrench.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MEKANIK");

        javax.swing.GroupLayout roundPanel3Layout = new javax.swing.GroupLayout(roundPanel3);
        roundPanel3.setLayout(roundPanel3Layout);
        roundPanel3Layout.setHorizontalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(116, Short.MAX_VALUE))
                    .addGroup(roundPanel3Layout.createSequentialGroup()
                        .addComponent(lb_mekanik)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23))))
        );
        roundPanel3Layout.setVerticalGroup(
            roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(lb_mekanik))
                .addGap(15, 15, 15))
        );

        roundPanel4.setBackground(new java.awt.Color(0, 153, 153));

        lb_stok.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_stok.setForeground(new java.awt.Color(255, 255, 255));
        lb_stok.setText("999");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/package.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ONDERDIL");

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(roundPanel4Layout.createSequentialGroup()
                        .addComponent(lb_stok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(24, 24, 24))))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(lb_stok))
                .addGap(15, 15, 15))
        );

        roundPanel5.setBackground(new java.awt.Color(0, 153, 153));

        lb_stokMenipis.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lb_stokMenipis.setForeground(new java.awt.Color(255, 255, 255));
        lb_stokMenipis.setText("999");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reject.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("STOK MENIPIS");

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(roundPanel5Layout.createSequentialGroup()
                        .addComponent(lb_stokMenipis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(25, 25, 25))))
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(lb_stokMenipis))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pnLayout = new javax.swing.GroupLayout(pn);
        pn.setLayout(pnLayout);
        pnLayout.setHorizontalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLayout.createSequentialGroup()
                        .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(roundPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(roundPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(roundPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLayout.setVerticalGroup(
            pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pn, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_kasir;
    private javax.swing.JLabel lb_mekanik;
    private javax.swing.JLabel lb_stok;
    private javax.swing.JLabel lb_stokMenipis;
    private javax.swing.JPanel pn;
    private roundpanel.RoundPanel roundPanel1;
    private roundpanel.RoundPanel roundPanel3;
    private roundpanel.RoundPanel roundPanel4;
    private roundpanel.RoundPanel roundPanel5;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private tablecustom.tablez tbl_data;
    // End of variables declaration//GEN-END:variables

    private void hitungJumlahDataBarang() {
        PreparedStatement st = null;
        ResultSet rs = null;

        try {
            // Query untuk mengambil jumlah data dari tabel barang tanpa filter
            String countSql = "SELECT COUNT(*) AS total FROM onderdil";
            st = conn.prepareStatement(countSql);
            rs = st.executeQuery();

            if (rs.next()) {
                // Ambil jumlah data dari hasil query dan konversi menjadi String
                String jumlahData = Integer.toString(rs.getInt("total"));

                // Set nilai lb_jmhBarang dengan jumlahData
                lb_stok.setText(jumlahData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void hitungJumlahDataMenipis() {
        PreparedStatement st = null;
        ResultSet rs = null;

        try {
            // Query untuk mengambil jumlah data dari tabel barang tanpa filter
            String countSql = "SELECT COUNT(*) AS total FROM onderdil WHERE stok <= 5";
            st = conn.prepareStatement(countSql);
            rs = st.executeQuery();

            if (rs.next()) {
                // Ambil jumlah data dari hasil query dan konversi menjadi String
                String jumlahData = Integer.toString(rs.getInt("total"));

                // Set nilai lb_jmhBarang dengan jumlahData
                lb_stokMenipis.setText(jumlahData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void hitungJumlahMekanik() {
        PreparedStatement st = null;
        ResultSet rs = null;

        try {
            // Query untuk mengambil jumlah data dari tabel barang tanpa filter
            String countSql = "SELECT COUNT(*) AS total FROM mekanik";
            st = conn.prepareStatement(countSql);
            rs = st.executeQuery();

            if (rs.next()) {
                // Ambil jumlah data dari hasil query dan konversi menjadi String
                String jumlahData = Integer.toString(rs.getInt("total"));

                // Set nilai lb_jmhBarang dengan jumlahData
                lb_mekanik.setText(jumlahData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void hitungJumlahKasir() {
        PreparedStatement st = null;
        ResultSet rs = null;

        try {
            // Query untuk mengambil jumlah data dari tabel barang tanpa filter
            String countSql = "SELECT COUNT(*) AS total FROM kasir";
            st = conn.prepareStatement(countSql);
            rs = st.executeQuery();

            if (rs.next()) {
                // Ambil jumlah data dari hasil query dan konversi menjadi String
                String jumlahData = Integer.toString(rs.getInt("total"));

                // Set nilai lb_jmhBarang dengan jumlahData
                lb_kasir.setText(jumlahData);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    private void loadData() {
        List<model_service> list = servis.ambilData();
        tblModel.setData(list);
    }
}
