/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.DAO_kasir;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumnModel;
import model.model_kasir;
import service.service_kasir;
import tableModel.table_kasir;

/**
 *
 * @author SyafiqUbai
 */
public class kasir extends javax.swing.JPanel {

    private service_kasir servis = new DAO_kasir();
    table_kasir tblMod = new table_kasir();

    /**
     * Creates new form customer_master
     */
    public kasir() {
        initComponents();

        tbl_cont.setModel(tblMod);
        btn_search.requestFocus();
        setColWidht();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataKasir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        scrollPaneWin111 = new custom.ScrollPaneWin11();
        tbl_cont = new tablecustom.tablez();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        tf_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JLabel();
        tambahKasir = new javax.swing.JPanel();
        btn_bersih = new rojerusan.RSMaterialButtonRectangle();
        btn_simpan = new rojerusan.RSMaterialButtonRectangle();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tf_kode = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_alamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_telp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(1300, 720));
        mainPanel.setLayout(new java.awt.CardLayout());

        dataKasir.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Data Kasir");

        btn_hapus.setBackground(new java.awt.Color(204, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        scrollPaneWin111.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneWin111.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        tbl_cont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cont.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbl_cont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_contMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_cont);

        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        tf_search.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tf_search.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_search.setText("Search");
        tf_search.setBorder(null);
        tf_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_searchFocusLost(evt);
            }
        });
        tf_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_searchMouseClicked(evt);
            }
        });
        tf_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_searchKeyPressed(evt);
            }
        });

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dataKasirLayout = new javax.swing.GroupLayout(dataKasir);
        dataKasir.setLayout(dataKasirLayout);
        dataKasirLayout.setHorizontalGroup(
            dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKasirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKasirLayout.createSequentialGroup()
                .addGroup(dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dataKasirLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 568, Short.MAX_VALUE)
                        .addComponent(btn_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataKasirLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataKasirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addGap(22, 22, 22))
        );
        dataKasirLayout.setVerticalGroup(
            dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKasirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_search)
                        .addComponent(tf_search, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(dataKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(dataKasir, "card2");

        tambahKasir.setBackground(new java.awt.Color(255, 255, 255));

        btn_bersih.setBackground(new java.awt.Color(204, 0, 0));
        btn_bersih.setText("CLEAR");
        btn_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihActionPerformed(evt);
            }
        });

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("Tambah Data Kasir");

        tf_kode.setEditable(false);
        tf_kode.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tf_kode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kodeActionPerformed(evt);
            }
        });

        tf_nama.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tf_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_namaKeyTyped(evt);
            }
        });

        tf_email.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tf_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_emailKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Id Kasir  :");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setText("Nama Kasir  :");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setText("No. Telp  :");

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setText("Email  :");

        tf_alamat.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tf_alamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_alamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_alamatKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Alamat :");

        tf_telp.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tf_telp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        tf_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_telpActionPerformed(evt);
            }
        });
        tf_telp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_telpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout tambahKasirLayout = new javax.swing.GroupLayout(tambahKasir);
        tambahKasir.setLayout(tambahKasirLayout);
        tambahKasirLayout.setHorizontalGroup(
            tambahKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tf_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8))
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(tf_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        tambahKasirLayout.setVerticalGroup(
            tambahKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahKasirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(tambahKasirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(tf_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(11, 11, 11)
                .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(tf_telp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(tf_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(tambahKasir, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_cont.getSelectedRow();
        if (x.equals("TAMBAH")) {

            jLabel2.setText("Tambah Data Kasir");

            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahKasir);
            mainPanel.repaint();
            mainPanel.revalidate();
            tf_kode.setText(servis.nomor());
            loadData();
        } else {
            int index = tbl_cont.getSelectedRow();
            if (index != -1) {
                model_kasir mod = tblMod.getData(tbl_cont.convertRowIndexToModel(index));

                if (x.equals("UBAH")) {
                    dataTable();
                    loadData();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
            }
        }


    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int index = tbl_cont.getSelectedRow();
        if (index != -1) {
            model_kasir mod = tblMod.getData(tbl_cont.convertRowIndexToModel(index));

            if (JOptionPane.showConfirmDialog(null, "Yakin Data Akan Dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(mod);
                tblMod.hapusData(index);
                loadData();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan dihapus");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        mainPanel.requestFocus();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihActionPerformed
        String x = btn_bersih.getText();
        if (x.equals("CLEAR")) {
            tf_nama.setText("");
            tf_telp.setText("");
            tf_email.setText("");
            tf_alamat.setText("");
        } else {
            clear();
            reset();

        }
        btn_bersih.setText("CLEAR");
        btn_batal1.setVisible(true);

    }//GEN-LAST:event_btn_bersihActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String x = btn_simpan.getText();
        int row = tbl_cont.getSelectedRow();
        if (x.equals("SIMPAN")) {
            if (validasiIn()) {
                String kode = tf_kode.getText();
                String nama = tf_nama.getText();
                String telp = tf_telp.getText();
                String email = tf_email.getText();
                String alamat = tf_alamat.getText();

                model_kasir mod = new model_kasir();

                mod.setId_kasir(kode);
                mod.setNama_kasir(nama);
                mod.setTelp_kasir(telp);
                mod.setEmail_kasir(email);
                mod.setAlamat_kasir(alamat);

                servis.tambahData(mod);
                tblMod.tambahData(mod);
                loadData();
                reset();
                clear();
            }
        } else {
            if (validasiIn()) {
                String kode = tf_kode.getText();
                String nama = tf_nama.getText();
                String telp = tf_telp.getText();
                String email = tf_email.getText();
                String alamat = tf_alamat.getText();

                model_kasir mod = new model_kasir();

                mod.setId_kasir(kode);
                mod.setNama_kasir(nama);
                mod.setTelp_kasir(telp);
                mod.setEmail_kasir(email);
                mod.setAlamat_kasir(alamat);

                servis.ubahData(mod);
                tblMod.perbaruiData(mod);
                loadData();
                reset();
                clear();
                btn_bersih.setText("CLEAR");
                btn_batal1.setVisible(true);
            }
        }


    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        clear();
        reset();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void tf_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kodeActionPerformed

    private void tbl_contMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_contMouseClicked
        if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }
        btn_hapus.setVisible(true);
        btn_batal.setVisible(true);
    }//GEN-LAST:event_tbl_contMouseClicked

    private void btn_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseClicked
        String x = tf_search.getText();
        if (x.equals("Search") || x.trim().equals("")) {
            loadData();
        } else {
            List<model_kasir> list = servis.pencarianData(x);
            tblMod.setData(list);
        }
    }//GEN-LAST:event_btn_searchMouseClicked

    private void tf_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_namaKeyTyped

    }//GEN-LAST:event_tf_namaKeyTyped

    private void tf_alamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_alamatKeyTyped

    }//GEN-LAST:event_tf_alamatKeyTyped

    private void tf_searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_searchKeyPressed
        pencarian();
    }//GEN-LAST:event_tf_searchKeyPressed

    private void tf_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_searchMouseClicked

    }//GEN-LAST:event_tf_searchMouseClicked

    private void tf_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_searchFocusGained
        String username = tf_search.getText();
        if (username.equals("Search")) {
            tf_search.setText("");
        }
    }//GEN-LAST:event_tf_searchFocusGained

    private void tf_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_searchFocusLost
        String user = tf_search.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            tf_search.setText("Search");
        }
    }//GEN-LAST:event_tf_searchFocusLost

    private void tf_telpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_telpKeyTyped
       char c = evt.getKeyChar();
        if (!((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Masukan hanya bilangan angka !");

            evt.consume();
        }
    }//GEN-LAST:event_tf_telpKeyTyped

    private void tf_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emailKeyTyped

    }//GEN-LAST:event_tf_emailKeyTyped

    private void tf_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_telpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_bersih;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private javax.swing.JLabel btn_search;
    private rojerusan.RSMaterialButtonRectangle btn_simpan;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private javax.swing.JPanel dataKasir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel mainPanel;
    private custom.ScrollPaneWin11 scrollPaneWin111;
    private javax.swing.JPanel tambahKasir;
    private tablecustom.tablez tbl_cont;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_kode;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_search;
    private javax.swing.JTextField tf_telp;
    // End of variables declaration//GEN-END:variables

    private boolean validasiIn() {
    boolean valid = false;
    
    if (tf_kode.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "ID Kasir tidak boleh kosong");
    } else if (tf_nama.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nama Kasir tidak boleh kosong");
    } else if (tf_telp.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "No.Telp tidak boleh kosong");
    } else if (tf_email.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Email tidak boleh kosong");
    } else if (!tf_email.getText().trim().endsWith("@gmail.com")) {
        JOptionPane.showMessageDialog(null, "Email harus diakhiri dengan @gmail.com");
    } else if (tf_alamat.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong");
    } else {
        valid = true;
    }
    
    return valid;
}


    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        List<model_kasir> list = servis.ambilData();
        tblMod.setData(list);
        if (btn_tambah.getText().equals("UBAH")) {
            btn_tambah.setText("TAMBAH");
        }
    }


    private void clear() {
        btn_simpan.setText("SIMPAN");
        tf_nama.setText("");
        tf_telp.setText("");
        tf_email.setText("");
        tf_alamat.setText("");
    }
    
        private void setColWidht() {
        int[] noCol = {0, 1, 2, 3};
        int[] noColW = {50, 90, 150, 150};

        TableColumnModel tblModel = tbl_cont.getColumnModel();
        for (int i = 0; i < noCol.length; i++) {
            tblModel.getColumn(noCol[i]).setPreferredWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMaxWidth(noColW[i]);
            tblModel.getColumn(noCol[i]).setMinWidth(noColW[i]);
        }

    }

    private void dataTable() {
        dataKasir.setVisible(false);
        tambahKasir.setVisible(true);

        int row = tbl_cont.getSelectedRow();
        jLabel2.setText("Perbarui Data Kasir");

        tf_kode.setText(tbl_cont.getModel().getValueAt(row, 1).toString());
        tf_nama.setText(tbl_cont.getModel().getValueAt(row, 2).toString());
        tf_telp.setText(tbl_cont.getModel().getValueAt(row, 3).toString());
        tf_email.setText(tbl_cont.getModel().getValueAt(row, 4).toString());
        tf_alamat.setText(tbl_cont.getModel().getValueAt(row, 5).toString());

        aktif();
        btn_simpan.setText("PERBARUI");
        btn_bersih.setText("BATAL");
        btn_batal1.setVisible(false);

        mainPanel.removeAll();
        mainPanel.add(tambahKasir);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void aktif() {
        tf_kode.setEnabled(false);
        tf_nama.setEnabled(true);
        tf_telp.setEnabled(true);
        tf_email.setEnabled(true);
        tf_alamat.setEnabled(true);
    }

    private void reset() {
        mainPanel.removeAll();
        mainPanel.add(dataKasir);
        mainPanel.repaint();
        mainPanel.revalidate();

        jLabel2.setText("Data Kasir");
        btn_simpan.setText("SIMPAN");
        btn_bersih.setEnabled(true);

    }

    private void pencarian() {
        List<model_kasir> list = servis.pencarianData(tf_search.getText().toLowerCase());
        tblMod.setData(list);
    }
}
