/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import config.koneksi;
import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SyafiqUbai
 */
public class Laporan extends javax.swing.JPanel {
    public Laporan() {
        initComponents();
        main.setVisible(true);
        mainService.setVisible(false);
        mainSupply.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        pn_pilihLaporan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        mainService = new javax.swing.JPanel();
        btn_printService = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        mainSupply = new javax.swing.JPanel();
        btn_printSupply = new rojerusan.RSMaterialButtonRectangle();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        cb_pilih = new rojerusan.RSComboMetro();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        jLabel1 = new javax.swing.JLabel();
        pn_tampil = new javax.swing.JPanel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        pn_pilihLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_pilihLaporan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pn_pilihLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Jenis Laporan");
        pn_pilihLaporan.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, -1));

        main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 215, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        pn_pilihLaporan.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 89, -1, -1));

        mainService.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_printService.setBackground(new java.awt.Color(204, 204, 0));
        btn_printService.setText("PRINT");
        btn_printService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printServiceActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal Awal");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setText("Tanggal Ahir");

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jDateChooser2.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout mainServiceLayout = new javax.swing.GroupLayout(mainService);
        mainService.setLayout(mainServiceLayout);
        mainServiceLayout.setHorizontalGroup(
            mainServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainServiceLayout.createSequentialGroup()
                .addGroup(mainServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainServiceLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_printService, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainServiceLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        mainServiceLayout.setVerticalGroup(
            mainServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainServiceLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_printService, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_pilihLaporan.add(mainService, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 89, -1, -1));

        mainSupply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_printSupply.setBackground(new java.awt.Color(204, 204, 0));
        btn_printSupply.setText("PRINT");
        btn_printSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printSupplyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal Awal");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Ahir");

        jDateChooser3.setDateFormatString("dd-MM-yyyy");

        jDateChooser4.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout mainSupplyLayout = new javax.swing.GroupLayout(mainSupply);
        mainSupply.setLayout(mainSupplyLayout);
        mainSupplyLayout.setHorizontalGroup(
            mainSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSupplyLayout.createSequentialGroup()
                .addGroup(mainSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSupplyLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btn_printSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainSupplyLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        mainSupplyLayout.setVerticalGroup(
            mainSupplyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainSupplyLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_printSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_pilihLaporan.add(mainSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 89, -1, -1));

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-pilih jenis laporan-", "service", "supply" }));
        cb_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pilihActionPerformed(evt);
            }
        });
        pn_pilihLaporan.add(cb_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 102, 102));
        rSMaterialButtonRectangle1.setText("KEMBALI");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        pn_pilihLaporan.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 307, 220, 40));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Laporan Riwayat Service & Supply");

        javax.swing.GroupLayout pn_tampilLayout = new javax.swing.GroupLayout(pn_tampil);
        pn_tampil.setLayout(pn_tampilLayout);
        pn_tampilLayout.setHorizontalGroup(
            pn_tampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        pn_tampilLayout.setVerticalGroup(
            pn_tampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pn_tampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_pilihLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_tampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        pn_tampil.removeAll();
        cb_pilih.setSelectedIndex(0);
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void btn_printServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printServiceActionPerformed
        try {
            String path = "src/report/laporan_service.jrxml";
            JasperReport jasperReport = null;
            SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");

            jasperReport = JasperCompileManager.compileReport(path);

            HashMap<String, Object> par = new HashMap<>();
            par.put("tglAwal", jDateChooser1.getDate());
            par.put("tglAkhir", jDateChooser2.getDate());
            JasperPrint print = JasperFillManager.fillReport(jasperReport, par, koneksi.getConnection());

            // Create JRViewer and set its properties
            JRViewer jrViewer = new JRViewer(print);
            jrViewer.setOpaque(true);
            jrViewer.setVisible(true);

            // Remove  pn_tampil
            pn_tampil.removeAll();

            // Set layout and add the JRViewer to pn_tampil
            pn_tampil.setLayout(new BorderLayout());
            pn_tampil.add(jrViewer, BorderLayout.CENTER);
            pn_tampil.revalidate();
            pn_tampil.repaint();

        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_printServiceActionPerformed

    private void cb_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pilihActionPerformed
        if (cb_pilih.getSelectedIndex() == 1) {
            main.setVisible(false);
            mainService.setVisible(true);
            mainSupply.setVisible(false);
        } else if (cb_pilih.getSelectedIndex() == 2) {
            main.setVisible(false);
            mainService.setVisible(false);
            mainSupply.setVisible(true);
        } else if (cb_pilih.getSelectedIndex() == 0) {
            main.setVisible(true);
            mainService.setVisible(false);
            mainSupply.setVisible(false);
        }
    }//GEN-LAST:event_cb_pilihActionPerformed

    private void btn_printSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printSupplyActionPerformed
        try {
            String path = "src/report/laporan_supply.jrxml";
            JasperReport jasperReport = null;
            SimpleDateFormat tgl = new SimpleDateFormat("dd-MM-yyyy");

            jasperReport = JasperCompileManager.compileReport(path);

            HashMap<String, Object> par = new HashMap<>();
            par.put("tglAwal", jDateChooser3.getDate());
            par.put("tglAkhir", jDateChooser4.getDate());
            JasperPrint print = JasperFillManager.fillReport(jasperReport, par, koneksi.getConnection());

            // Create JRViewer and set its properties
            JRViewer jrViewer = new JRViewer(print);
            jrViewer.setOpaque(true);
            jrViewer.setVisible(true);

            // Remove existing components from pn_tampil
            pn_tampil.removeAll();

            // Set layout and add the JRViewer to pn_tampil
            pn_tampil.setLayout(new BorderLayout());
            pn_tampil.add(jrViewer, BorderLayout.CENTER);
            pn_tampil.revalidate();
            pn_tampil.repaint();

        } catch (JRException ex) {
            Logger.getLogger(Laporan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_printSupplyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_printService;
    private rojerusan.RSMaterialButtonRectangle btn_printSupply;
    private rojerusan.RSComboMetro cb_pilih;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainService;
    private javax.swing.JPanel mainSupply;
    private javax.swing.JPanel pn_pilihLaporan;
    private javax.swing.JPanel pn_tampil;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JPanel tampilData;
    // End of variables declaration//GEN-END:variables
}
