package view;

import config.koneksi;
import dao.DAO_detailService;
import dao.DAO_pembayaranService;
import dao.DAO_service;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import model.model_detailService;
import model.model_detailSupply;
import model.model_kasir;
import model.model_pembayaranService;
import model.model_pembayaranSupply;
import model.model_service;
import model.model_supply;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import service.service_detailService;
import service.service_pembayaranService;
import service.service_service;
import tableModel.table_detailService;
import tableModel.table_pembayaranService;
import tableModel.table_service;

public class pembayaran_service extends javax.swing.JPanel {
    
    private Connection conn;

    private service_pembayaranService service = new DAO_pembayaranService();
    private table_pembayaranService tblModel = new table_pembayaranService();
    
    private service_service servis_sup = new DAO_service();
    private table_service tbl_sup = new table_service();

    private service_detailService servis_det = new DAO_detailService();
    private table_detailService tbl_det = new table_detailService();
    private table_detailService tbl_det2 = new table_detailService();

    public pembayaran_service() {
        initComponents();
        conn = koneksi.getConnection();
        tbl_data.setModel(tblModel);
        tbl_detail.setModel(tbl_det);
        tbl_detail2.setModel(tbl_det2);

        loadData();
        pn_detail.setVisible(false);
        btn_lunasi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        status = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        t_pencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        scrollPaneWin112 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail = new tablecustom.tablez();
        jLabel2 = new javax.swing.JLabel();
        tf_kodeService = new javax.swing.JTextField();
        tf_idBarangCus = new javax.swing.JTextField();
        tf_namaCus = new javax.swing.JTextField();
        tf_tglService = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        harga_jasa = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        btn_print = new rojerusan.RSMaterialButtonRectangle();
        tambahData = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();
        btn_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel2 = new javax.swing.JPanel();
        t_tglPembayaran = new javax.swing.JTextField();
        t_kodepembayaran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scrollPaneWin113 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail2 = new tablecustom.tablez();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        t_kodeService = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        t_idBarang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        t_tgService = new javax.swing.JTextField();
        t_namaCustomer = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        t_total = new javax.swing.JTextField();
        t_status = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cb_bayar = new rojerusan.RSComboMetro();
        t_bayar = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        t_kekurangan = new javax.swing.JTextField();
        t_dp = new javax.swing.JTextField();
        t_sudahBayar = new javax.swing.JTextField();
        lb_persen = new javax.swing.JLabel();
        lb_dpbayar = new javax.swing.JLabel();
        btn_lunasi = new javax.swing.JButton();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        jPanel4 = new javax.swing.JPanel();
        t_namaKasir = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_pilihKasir = new javax.swing.JButton();
        t_idKasir = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_pilihService = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_data);

        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(204, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        t_pencarian.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        t_pencarian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_pencarian.setText("Search");
        t_pencarian.setBorder(null);
        t_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_pencarianFocusLost(evt);
            }
        });
        t_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_pencarianKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_pencarianKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(255, 102, 102));

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin112.setViewportView(tbl_detail);

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        tf_kodeService.setEditable(false);
        tf_kodeService.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tf_kodeService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_kodeService.setText(" ");

        tf_idBarangCus.setEditable(false);
        tf_idBarangCus.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tf_idBarangCus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_idBarangCus.setText(" ");

        tf_namaCus.setEditable(false);
        tf_namaCus.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tf_namaCus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_namaCus.setText(" ");

        tf_tglService.setEditable(false);
        tf_tglService.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tf_tglService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_tglService.setText(" ");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kode Service");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Nama Customer");

        jLabel17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("ID Barang Customer");

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Tgl Service");

        harga_jasa.setEditable(false);
        harga_jasa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        harga_jasa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        harga_jasa.setText("0");

        jLabel24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Harga Jasa");

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_detailLayout.createSequentialGroup()
                        .addComponent(tf_kodeService, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tf_idBarangCus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tf_namaCus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tf_tglService, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga_jasa))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(scrollPaneWin112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_kodeService, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_idBarangCus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_namaCus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tglService, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga_jasa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin112, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        judul1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul1.setText("Pembayaran Service");

        btn_print.setBackground(new java.awt.Color(204, 204, 0));
        btn_print.setText("PRINT");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tampilDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addGap(20, 20, 20))
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judul1)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_pencarian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        judul2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul2.setText("Tambah Pembayaran");

        btn_tambah1.setText("TAMBAH");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_tglPembayaran.setEditable(false);
        t_tglPembayaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_tglPembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_kodepembayaran.setEditable(false);
        t_kodepembayaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_kodepembayaran.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kodepembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_kodepembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodepembayaranActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kode Pembayaran");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_kodepembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_tglPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_kodepembayaran)
                    .addComponent(t_tglPembayaran))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        scrollPaneWin113.setBackground(new java.awt.Color(255, 255, 255));

        tbl_detail2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_detail2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        scrollPaneWin113.setViewportView(tbl_detail2);

        jPanel6.setBackground(new java.awt.Color(255, 102, 102));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Kode Service");

        t_kodeService.setEditable(false);
        t_kodeService.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kodeService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeServiceActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ID Barang Customer");

        t_idBarang.setEditable(false);
        t_idBarang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Tgl Service");

        t_tgService.setEditable(false);
        t_tgService.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t_namaCustomer.setEditable(false);
        t_namaCustomer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Nama Customer");

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Total Service");

        t_total.setEditable(false);
        t_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        t_status.setEditable(false);
        t_status.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel28.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Status");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_kodeService, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_namaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_tgService, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_total)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_status, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_namaCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_tgService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_idBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_kodeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PEMBAYARAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 486, -1));

        cb_bayar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-pilih bayar-", "DP", "Lunas" }));
        cb_bayar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cb_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(cb_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 49, 149, 25));

        t_bayar.setEditable(false);
        t_bayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(t_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 147, 25));

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Total Service :");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 147, 25));

        jLabel27.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Kekurangan bayar :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 85, 147, 25));

        t_kekurangan.setEditable(false);
        t_kekurangan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kekurangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kekuranganActionPerformed(evt);
            }
        });
        jPanel1.add(t_kekurangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 85, 147, 25));

        t_dp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_dp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_dpKeyReleased(evt);
            }
        });
        jPanel1.add(t_dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 85, 50, 25));

        t_sudahBayar.setEditable(false);
        t_sudahBayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_sudahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_sudahBayarActionPerformed(evt);
            }
        });
        jPanel1.add(t_sudahBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 147, 25));

        lb_persen.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lb_persen.setText("%");
        jPanel1.add(lb_persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 85, 45, 25));

        lb_dpbayar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb_dpbayar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_dpbayar.setText("Yang di bayar :");
        jPanel1.add(lb_dpbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 124, 147, -1));

        btn_lunasi.setText("Lunasi pembayaran");
        btn_lunasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lunasiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lunasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 150, -1));

        btn_batal1.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_namaKasir.setEditable(false);
        t_namaKasir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_namaKasir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nama Kasir");

        btn_pilihKasir.setText("jButton1");
        btn_pilihKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihKasirActionPerformed(evt);
            }
        });

        t_idKasir.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID Kasir :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_idKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(t_namaKasir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pilihKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_namaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pilihKasir)
                    .addComponent(t_idKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SERVICE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        btn_pilihService.setText("*pilih service yg di bayar");
        btn_pilihService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pilihServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_pilihService, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_pilihService)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tambahDataLayout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tambahDataLayout.createSequentialGroup()
                                            .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(tambahDataLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(tambahDataLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(judul2))
                                .addGroup(tambahDataLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(judul2)
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin113, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        if (btn_tambah.getText().equals("TAMBAH")) {
            btn_tambah.setText("UBAH");
        }
        btn_hapus.setVisible(true); 
        btn_batal.setVisible(true);
        btn_print.setVisible(true);
        pn_detail.setVisible(true);
        model_service sp = new model_service();

        int row = tbl_data.getSelectedRow();
        String id = tbl_data.getModel().getValueAt(row, 1).toString();
        List<model_service> list = servis_sup.getByID(id);
        sp = list.get(0);
        
        tf_kodeService.setText(sp.getKode_service());
        tf_idBarangCus.setText(sp.getBarangcus().getKode_barang());
        tf_namaCus.setText(sp.getBarangcus().getNama_customer());
        tf_tglService.setText(String.valueOf(sp.getTgl_service()));
        harga_jasa.setText(String.valueOf(sp.getHarga_service()));
        detail();
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_data.getSelectedRow();
        
        if (x.equals("TAMBAH")) {

            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahData);
            mainPanel.repaint();
            mainPanel.revalidate();
            t_dp.setVisible(false);
            lb_persen.setVisible(false);
            t_sudahBayar.setVisible(false);
            lb_dpbayar.setVisible(false);
            judul2.setText("Tambah Pembayaran");
            btn_tambah1.setText("SIMPAN");

            t_kodepembayaran.setText(service.nomor());
            setTanggal();
            loadData();
            risetTambah();
        }else{
            int index = tbl_data.getSelectedRow();
            if (index != -1) {
                model_pembayaranService mod = tblModel.getData(tbl_data.convertRowIndexToModel(index));

                if (x.equals("UBAH")) {
                    dataTable();
                    loadData();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
            }
        }
        
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
            
            btn_tambah1.setText("TAMBAH");
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
            perbaruiData();
        }
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void t_pencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pencarianKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pencarianKeyTyped

    private void t_pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pencarianKeyPressed
        pencarian();
    }//GEN-LAST:event_t_pencarianKeyPressed

    private void t_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusGained
        String username = t_pencarian.getText();
        if (username.equals("Search")) {
            t_pencarian.setText("");
        }
    }//GEN-LAST:event_t_pencarianFocusGained

    private void t_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusLost
        String user = t_pencarian.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            t_pencarian.setText("Search");
        }
    }//GEN-LAST:event_t_pencarianFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
//        tampilPanel();
        pn_detail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t_kodepembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodepembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodepembayaranActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData(); 
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void t_kodeServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeServiceActionPerformed

    private void t_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_bayarActionPerformed

    private void t_kekuranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kekuranganActionPerformed
        
        
    }//GEN-LAST:event_t_kekuranganActionPerformed

    private void btn_pilihKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihKasirActionPerformed
        boolean closable = true;
        dialog_dataKasir spr = new dialog_dataKasir(null, closable);
        spr.setVisible(true);
        
        t_idKasir.setText(spr.ks.getId_kasir());
        t_namaKasir.setText(spr.ks.getNama_kasir());
        
        btn_pilihService.requestFocus();
    }//GEN-LAST:event_btn_pilihKasirActionPerformed

    private void cb_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bayarActionPerformed
        if (!t_total.getText().trim().isEmpty()) {
            double total;
            long kurang;

            total = Double.parseDouble(t_bayar.getText().replace(",", "")); // Parse without commas

            if (cb_bayar.getSelectedIndex() == 1) {
                t_dp.setVisible(true);
                t_status.setText("DP");
                t_dp.setVisible(true);
                lb_persen.setVisible(true);
                t_sudahBayar.setVisible(true);
                lb_dpbayar.setVisible(true);
                t_dp.requestFocus();
            } else if (cb_bayar.getSelectedIndex() == 2) {
                kurang = Math.round(total - total);
                t_sudahBayar.setText(t_bayar.getText());
                t_kekurangan.setText(Long.toString(kurang));
                t_status.setText("Lunas");
                t_dp.setVisible(false);
                lb_persen.setVisible(false);
//                t_sudahBayar.setVisible(false);
//                lb_dpbayar.setVisible(false);
            } else if (cb_bayar.getSelectedIndex() == 0) {
                t_dp.setVisible(false);
                lb_persen.setVisible(false);
//                t_sudahBayar.setVisible(false);
//                lb_dpbayar.setVisible(false);
            }
        } else {
            cb_bayar.setSelectedIndex(0);
            t_dp.setVisible(false);
            lb_persen.setVisible(false);
            t_sudahBayar.setVisible(false);
            lb_dpbayar.setVisible(false);
            JOptionPane.showMessageDialog(null, "Masukkan Supply yang akan dibayar!!!");
        }

    }//GEN-LAST:event_cb_bayarActionPerformed

    private void t_sudahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_sudahBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_sudahBayarActionPerformed

    private void t_dpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_dpKeyReleased
        if (Integer.parseInt(t_dp.getText()) <= 100 && Integer.parseInt(t_dp.getText()) >= 0) {
            Long total, dp, tdp, kurang;
            total = Long.valueOf(t_total.getText().replace(",", ""));
            dp = Long.parseLong(t_dp.getText());
            kurang = total - (total * dp / 100);
            tdp =total * dp/100;
            t_kekurangan.setText(Long.toString(kurang));
            t_sudahBayar.setText(Long.toString(tdp));
        } else {
            JOptionPane.showMessageDialog(null, "Silakan masukkan angka antara 0-100");
            t_dp.setText(String.valueOf(""));
        }
    }//GEN-LAST:event_t_dpKeyReleased

    private void btn_pilihServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pilihServiceActionPerformed
        boolean closable = true;
        dialog_dataService ds = new dialog_dataService(null, closable);
        ds.setVisible(true);

        t_kodeService.setText(ds.sv.getKode_service());
        t_idBarang.setText(ds.sv.getBarangcus().getKode_barang());
        t_namaCustomer.setText(ds.sv.getBarangcus().getNama_customer());
        // Format the Date to a String before setting it to the text field
        Date tglServiceDate = ds.sv.getTgl_service();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); // You can customize the format
        String formattedDate = dateFormat.format(tglServiceDate);
        t_tgService.setText(formattedDate);
        t_total.setText(String.valueOf(ds.sv.getTotal()));
        
        String id = t_kodeService.getText();
        List<model_detailService> list = servis_det.getByID(id);
        tbl_det2.setData(list);

        t_bayar.setText(String.valueOf(t_total.getText()));
    }//GEN-LAST:event_btn_pilihServiceActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        try {

            String reportPath = new String("/report/pembayaran_service.jrxml");

            int row = tbl_data.getSelectedRow();
            String id = tbl_data.getModel().getValueAt(row, 0).toString();
            String id_det = tbl_data.getModel().getValueAt(row, 1).toString();
            
            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("id_pembayaranService", id);
            parameters.put("id_det", id_det);

            JasperPrint print = JasperFillManager.fillReport(
            JasperCompileManager.compileReport(getClass().getResourceAsStream(reportPath)), parameters, conn);

            JasperViewer.viewReport(print, false);
        } catch (JRException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_lunasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lunasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_lunasiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private javax.swing.JButton btn_lunasi;
    private javax.swing.JButton btn_pilihKasir;
    private javax.swing.JButton btn_pilihService;
    private rojerusan.RSMaterialButtonRectangle btn_print;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambah1;
    private rojerusan.RSComboMetro cb_bayar;
    private javax.swing.JTextField harga_jasa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel lb_dpbayar;
    private javax.swing.JLabel lb_persen;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin112;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin113;
    private javax.swing.ButtonGroup status;
    private javax.swing.JTextField t_bayar;
    private javax.swing.JTextField t_dp;
    private javax.swing.JTextField t_idBarang;
    private javax.swing.JTextField t_idKasir;
    private javax.swing.JTextField t_kekurangan;
    private javax.swing.JTextField t_kodeService;
    private javax.swing.JTextField t_kodepembayaran;
    private javax.swing.JTextField t_namaCustomer;
    private javax.swing.JTextField t_namaKasir;
    private javax.swing.JTextField t_pencarian;
    private javax.swing.JTextField t_status;
    private javax.swing.JTextField t_sudahBayar;
    private javax.swing.JTextField t_tgService;
    private javax.swing.JTextField t_tglPembayaran;
    private javax.swing.JTextField t_total;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private tablecustom.tablez tbl_data;
    private tablecustom.tablez tbl_detail;
    private tablecustom.tablez tbl_detail2;
    private javax.swing.JTextField tf_idBarangCus;
    private javax.swing.JTextField tf_kodeService;
    private javax.swing.JTextField tf_namaCus;
    private javax.swing.JTextField tf_tglService;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_print.setVisible(false);
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        pn_detail.setVisible(false);
        List<model_pembayaranService> list = service.getData();
        tblModel.setData(list);
    }
    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new pembayaran_service());
        mainPanel.repaint();
        mainPanel.revalidate();
    }
    
    private void dataTable() {
        btn_batal1.setVisible(true);
        t_dp.setVisible(false);
        lb_persen.setVisible(false);
        int row = tbl_data.getSelectedRow();
        jLabel2.setText("Perbarui Pesanan");

        t_kodepembayaran.setText(tbl_data.getModel().getValueAt(row, 0).toString());
        t_kodeService.setText(tbl_data.getModel().getValueAt(row, 1).toString());
        t_idKasir.setText(tbl_data.getModel().getValueAt(row, 2).toString());
        t_namaKasir.setText(tbl_data.getModel().getValueAt(row, 3).toString());
        t_bayar.setText(tbl_data.getModel().getValueAt(row, 4).toString());
        t_sudahBayar.setText(tbl_data.getModel().getValueAt(row, 5).toString());
        t_kekurangan.setText(tbl_data.getModel().getValueAt(row, 6).toString());
        setTanggal();
        t_status.setText(tbl_data.getModel().getValueAt(row, 8).toString());
        
        
        

        btn_tambah1.setText("PERBARUI");

        mainPanel.removeAll();
        mainPanel.add(tambahData);
        mainPanel.repaint();
        mainPanel.revalidate();
        
        int rowi = tbl_data.getSelectedRow();

        List<model_service> liste = servis_sup.getByID(t_kodeService.getText());
        model_service ser = liste.get(0);

        t_kodeService.setText(ser.getKode_service());
        t_idBarang.setText(ser.getBarangcus().getKode_barang());
        t_namaCustomer.setText(ser.getBarangcus().getNama_customer());

        // Format the Date to a String before setting it to the text field
        Date tglServiceDate = ser.getTgl_service();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy"); // You can customize the format
        String formattedDate = dateFormat.format(tglServiceDate);
        t_tgService.setText(formattedDate);

        t_total.setText(String.valueOf(ser.getTotal()));

        String id = t_kodeService.getText();
        List<model_detailService> list = servis_det.getByID(id);
        tbl_det2.setData(list);

    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        tf_kodeService.setText("");
        tf_idBarangCus.setText("");
        tf_tglService.setText("");
        tf_namaCus.setText("");
        harga_jasa.setText("");
    }
    
    private void simpanData() {

        if (validasiIn() == true) {
            String kode = t_kodepembayaran.getText();
            String idKas = t_idKasir.getText();
            String kod_ser = t_kodeService.getText();
            String tgl = t_tglPembayaran.getText();
            Long kurang = Long.valueOf(t_kekurangan.getText());
            Long sudah = Long.valueOf(t_sudahBayar.getText());
            String status = t_status.getText();
            
            model_pembayaranService ps = new model_pembayaranService();
            model_kasir ks = new model_kasir();
            model_service s = new model_service();
            
            ps.setId_pembayaranservice(kode);
            ks.setId_kasir(idKas);
            s.setKode_service(kod_ser);
            try {
                // Parse the string date to java.util.Date
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Replace "your_date_format" with the actual date format
                Date tgldate = sdf.parse(tgl);
                ps.setTgl_pembayaranservice(tgldate); // Corrected line
            } catch (ParseException e) {
                e.printStackTrace(); // Handle the parsing exception appropriately
                return; // Return or handle error accordingly
            }
            ps.setKurang_bayar(kurang);
            ps.setSudah_bayar(sudah);
            ps.setStatus_pembayaran(status);
            

            ps.setModKa(ks);
            ps.setModService(s);

            tblModel.tambahData(ps);
            service.tambahData(ps);
            loadData();
            resetForm();
            tampilPanel();
        }
        
    }
    
    private boolean validasiIn() {
        boolean valid = false;
        if (t_kodepembayaran.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Pembayaran tidak boleh kosong");
        } else if (t_tglPembayaran.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tgl Pembayaran tidak boleh kosong");
        } else if (t_idKasir.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID kasir tidak boleh kosong");
        } else if (t_kodeService.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Service tidak boleh kosong");
        } else if (cb_bayar.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih dulu pembayaran yang diinginkan");
        } else {
            valid = true;
        }
        return valid;
    }

    
    private void hapusData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            model_pembayaranService spl = tblModel.getData(tbl_data.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                service.hapusData(spl);
                tblModel.hapusData(index);
                hapusdet();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private void pencarian() {
        List<model_pembayaranService> list = service.pencarianData(t_pencarian.getText().toLowerCase());
        tblModel.setData(list);
    }

    private void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        t_tglPembayaran.setText(kal.format(sekarang));
    }

    private void total() {
        int columnCount = tbl_detail2.getRowCount();
        int total = 0;

            for(int i = 0; i < columnCount; i++){
                total += Integer.parseInt(tbl_detail2.getValueAt(i, 4).toString());
            }
            t_total.setText(String.valueOf(total));
    }

    private void detail() {
        int row = tbl_data.getSelectedRow();
        String id = tbl_data.getModel().getValueAt(row, 1).toString();
        List<model_detailService> list = servis_det.getByID(id);
        tbl_det.setData(list);    
        
        
    }

    private void risetTambah() {
        t_kodeService.setText("");
        t_idBarang.setText("");
        t_tgService.setText("");
    }

    private void hapusdet() {
        // Mengambil ID dari tf_kodeSupply
        String kodeService = tf_kodeService.getText();

        if (!kodeService.isEmpty()) {
            // Membuat objek model_supply dengan ID yang diambil
            model_service s = new model_service();
            s.setKode_service(kodeService);

            // Menghapus data menggunakan servis_sup.hapusData
            servis_sup.hapusData(s);

            // Memperbarui tabel dan mereset formulir
            loadData();
            resetForm();
        }
    }

    private void perbaruiData() {
        if (validasiIn() == true) {
            String kode = t_kodepembayaran.getText();
            String idKas = t_idKasir.getText();
            String kod_ser = t_kodeService.getText();
            String tgl = t_tglPembayaran.getText();
            Long kurang = Long.valueOf(t_kekurangan.getText());
            Long sudah = Long.valueOf(t_sudahBayar.getText());
            String status = t_status.getText();
            
            model_pembayaranService ps = new model_pembayaranService();
            model_kasir ks = new model_kasir();
            model_service s = new model_service();
            
            ps.setId_pembayaranservice(kode);
            ks.setId_kasir(idKas);
            s.setKode_service(kod_ser);
            try {
                // Parse the string date to java.util.Date
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Replace "your_date_format" with the actual date format
                Date tgldate = sdf.parse(tgl);
                ps.setTgl_pembayaranservice(tgldate); // Corrected line
            } catch (ParseException e) {
                e.printStackTrace(); // Handle the parsing exception appropriately
                return; // Return or handle error accordingly
            }
            ps.setKurang_bayar(kurang);
            ps.setSudah_bayar(sudah);
            ps.setStatus_pembayaran(status);
            

            ps.setModKa(ks);
            ps.setModService(s);

            tblModel.tambahData(ps);
            service.ubahData(ps);
            loadData();
            resetForm();
            tampilPanel();
        }
    }
}
