package view;

import dao.DAO_detailSupply;
import dao.DAO_supply;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.model_detailSupply;
import model.model_onderdil;
import model.model_supplier;
import model.model_supply;
import service.service_detailSupply;
import service.service_supply;
import tableModel.table_detailSupply;
import tableModel.table_supply;

public class supply extends javax.swing.JPanel {

    private service_supply servis = new DAO_supply();
    private table_supply tblModel = new table_supply();

    private service_detailSupply servis_det = new DAO_detailSupply();
    private table_detailSupply tbl_det = new table_detailSupply();

    public supply() {
        initComponents();
        tbl_data.setModel(tblModel);
        tbl_detail.setModel(tbl_det);
        
        loadData();
        pn_detail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tampilData = new javax.swing.JPanel();
        scrollPaneWin111 = new scrollbarwin11.ScrollPaneWin11();
        tbl_data = new tablecustom.tablez();
        btn_tambah = new rojerusan.RSMaterialButtonRectangle();
        btn_hapus = new rojerusan.RSMaterialButtonRectangle();
        btn_batal = new rojerusan.RSMaterialButtonRectangle();
        jSeparator1 = new javax.swing.JSeparator();
        t_pencarian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pn_detail = new javax.swing.JPanel();
        scrollPaneWin112 = new scrollbarwin11.ScrollPaneWin11();
        tbl_detail = new tablecustom.tablez();
        judul3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        tambahData = new javax.swing.JPanel();
        judul2 = new javax.swing.JLabel();
        btn_tambah1 = new rojerusan.RSMaterialButtonRectangle();
        btn_clear = new rojerusan.RSMaterialButtonRectangle();
        btn_batal1 = new rojerusan.RSMaterialButtonRectangle();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        t_tglSupply = new javax.swing.JTextField();
        t_kodeSupply = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        t_idSupplier = new javax.swing.JTextField();
        t_namaSupplier = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_supplier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        t_kodeOnderdil = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        t_namaOnderdil = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        t_jumlah = new javax.swing.JTextField();
        btn_onderdil = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        t_subTotal = new javax.swing.JTextField();
        btn_perbarui = new rojerusan.RSMaterialButtonRectangle();
        btn_add = new rojerusan.RSMaterialButtonRectangle();
        btn_hapusSementara = new rojerusan.RSMaterialButtonRectangle();
        scrollPaneWin113 = new scrollbarwin11.ScrollPaneWin11();
        tbl_sementara = new tablecustom.tablez();
        jPanel6 = new javax.swing.JPanel();
        lb_total = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setLayout(new java.awt.CardLayout());

        tampilData.setBackground(new java.awt.Color(255, 255, 255));

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_dataMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tbl_data);

        btn_tambah.setText("TAMBAH");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(204, 0, 0));
        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal.setText("BATAL");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        t_pencarian.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        t_pencarian.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_pencarian.setText("Search");
        t_pencarian.setBorder(null);
        t_pencarian.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_pencarianFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_pencarianFocusLost(evt);
            }
        });
        t_pencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_pencarianKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_pencarianKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search (1).png"))); // NOI18N

        pn_detail.setBackground(new java.awt.Color(255, 255, 255));

        tbl_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneWin112.setViewportView(tbl_detail);

        judul3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul3.setText("Detail Data Supply");

        jLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_detailLayout = new javax.swing.GroupLayout(pn_detail);
        pn_detail.setLayout(pn_detailLayout);
        pn_detailLayout.setHorizontalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneWin112, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pn_detailLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_detailLayout.setVerticalGroup(
            pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_detailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judul3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneWin112, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        judul1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul1.setText("Data Supply");

        javax.swing.GroupLayout tampilDataLayout = new javax.swing.GroupLayout(tampilData);
        tampilData.setLayout(tampilDataLayout);
        tampilDataLayout.setHorizontalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 1102, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(tampilDataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tampilDataLayout.setVerticalGroup(
            tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tampilDataLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judul1)
                    .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t_pencarian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tampilDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(tampilData, "card2");

        tambahData.setBackground(new java.awt.Color(255, 255, 255));

        judul2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        judul2.setText("Tambah Data Onderdil");

        btn_tambah1.setText("TAMBAH");
        btn_tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah1ActionPerformed(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(204, 0, 0));
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_batal1.setBackground(new java.awt.Color(0, 153, 0));
        btn_batal1.setText("BATAL");
        btn_batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_tglSupply.setEditable(false);
        t_tglSupply.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_tglSupply.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_tglSupply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        t_kodeSupply.setEditable(false);
        t_kodeSupply.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_kodeSupply.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kodeSupply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_kodeSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeSupplyActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kode Supply");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tanggal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_kodeSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t_tglSupply)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t_kodeSupply)
                    .addComponent(t_tglSupply))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUPPLIER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        t_idSupplier.setEditable(false);
        t_idSupplier.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        t_idSupplier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_idSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_idSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idSupplierActionPerformed(evt);
            }
        });

        t_namaSupplier.setEditable(false);
        t_namaSupplier.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        t_namaSupplier.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_namaSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel8.setText("ID Supplier");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setText("Toko Supplier");

        btn_supplier.setText("...");
        btn_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(t_idSupplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(t_namaSupplier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_namaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_idSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Onderdil");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        t_kodeOnderdil.setEditable(false);
        t_kodeOnderdil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_kodeOnderdil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_kodeOnderdil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_kodeOnderdil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_kodeOnderdilActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel10.setText("Kode Onderdil");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel11.setText("Nama Onderdil");

        t_namaOnderdil.setEditable(false);
        t_namaOnderdil.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_namaOnderdil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_namaOnderdil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_namaOnderdil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaOnderdilActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel12.setText("Harga");

        t_harga.setEditable(false);
        t_harga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_hargaActionPerformed(evt);
            }
        });

        t_jumlah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jumlahActionPerformed(evt);
            }
        });

        btn_onderdil.setText("...");
        btn_onderdil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onderdilActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel15.setText("Jumlah");

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel16.setText("SubTotal");

        t_subTotal.setEditable(false);
        t_subTotal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        t_subTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_subTotal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                t_subTotalMouseMoved(evt);
            }
        });
        t_subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_subTotalActionPerformed(evt);
            }
        });

        btn_perbarui.setBackground(new java.awt.Color(0, 102, 0));
        btn_perbarui.setText("perbarui");
        btn_perbarui.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perbaruiActionPerformed(evt);
            }
        });

        btn_add.setText("Tambah Sementara");
        btn_add.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_hapusSementara.setBackground(new java.awt.Color(153, 0, 0));
        btn_hapusSementara.setText("hapus");
        btn_hapusSementara.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btn_hapusSementara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusSementaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btn_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hapusSementara, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t_kodeOnderdil))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_onderdil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(t_jumlah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_namaOnderdil, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(t_harga)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_onderdil)
                    .addComponent(t_kodeOnderdil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_namaOnderdil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hapusSementara, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_perbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPaneWin113.setBackground(new java.awt.Color(255, 255, 255));

        tbl_sementara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Onderdil", "Nama Onderdil", "Harga", "Jumlah Suppy", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sementara.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbl_sementara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sementaraMouseClicked(evt);
            }
        });
        scrollPaneWin113.setViewportView(tbl_sementara);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        lb_total.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lb_total.setText("Total Supply");

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel14.setText("Total Supply :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(lb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tambahDataLayout = new javax.swing.GroupLayout(tambahData);
        tambahData.setLayout(tambahDataLayout);
        tambahDataLayout.setHorizontalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(judul2))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1089, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tambahDataLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneWin113, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tambahDataLayout.setVerticalGroup(
            tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambahDataLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(judul2)
                .addGap(6, 6, 6)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(tambahDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambahDataLayout.createSequentialGroup()
                        .addComponent(scrollPaneWin113, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        mainPanel.add(tambahData, "card2");

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_dataMouseClicked
        btn_hapus.setVisible(true); 
        btn_batal.setVisible(true);
        int row = tbl_data.getSelectedRow();
        String id = tbl_data.getValueAt(row, 0).toString();

        pn_detail.setVisible(true);
        List<model_detailSupply> list = servis_det.getByID(id);
        tbl_det.setData(list);
    }//GEN-LAST:event_tbl_dataMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String x = btn_tambah.getText();
        int row = tbl_data.getSelectedRow();
        
        if (x.equals("TAMBAH")) {

            mainPanel.removeAll();
            mainPanel.repaint();
            mainPanel.revalidate();

            mainPanel.add(tambahData);
            mainPanel.repaint();
            mainPanel.revalidate();

            judul2.setText("Tambah Data Supply");
            btn_tambah1.setText("SIMPAN");
            
            t_kodeSupply.setText(servis.nomor());
            setTanggal();
            loadData();
        } else {
            int index = tbl_data.getSelectedRow();
            if (index != -1) {
                model_supply mod = tblModel.getData(tbl_data.convertRowIndexToModel(index));

                if (x.equals("UBAH")) {
                    dataTabel();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pilih dahulu data yang akan diubah");
            }
        }
        lb_total.setText("0");
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        hapusData();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        tampilPanel();
        loadData();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah1ActionPerformed
        if (btn_tambah1.getText().equals("TAMBAH")) {
            btn_tambah1.setText("SIMPAN");
        } else if (btn_tambah1.getText().equals("SIMPAN")) {
            simpanData();
            simpatDet();
            loadData();
            resetForm();
            tampilPanel();
            btn_tambah1.setText("TAMBAH");
        } else if (btn_tambah1.getText().equals("PERBARUI")) {
//            perbaruiData();
//              loadData();
        }
        
    }//GEN-LAST:event_btn_tambah1ActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        String x = btn_clear.getText();
        if (x.equals("CLEAR")) {
            clear();
        } else {
            tampilPanel();
            loadData();
            resetForm();

        }
        btn_clear.setText("CLEAR");
        btn_batal1.setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal1ActionPerformed
        tampilPanel();
        loadData();
        resetForm();
    }//GEN-LAST:event_btn_batal1ActionPerformed

    private void t_pencarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pencarianKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pencarianKeyTyped

    private void t_pencarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_pencarianKeyPressed
        pencarian();
    }//GEN-LAST:event_t_pencarianKeyPressed

    private void t_pencarianFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusGained
        String username = t_pencarian.getText();
        if (username.equals("Search")) {
            t_pencarian.setText("");
        }
    }//GEN-LAST:event_t_pencarianFocusGained

    private void t_pencarianFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_pencarianFocusLost
        String user = t_pencarian.getText();
        if (user.equalsIgnoreCase("Search") || user.equalsIgnoreCase("")) {
            t_pencarian.setText("Search");
        }
    }//GEN-LAST:event_t_pencarianFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        tampilPanel();
        pn_detail.setVisible(false);
        loadData();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t_kodeSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeSupplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeSupplyActionPerformed

    private void t_idSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idSupplierActionPerformed

    private void t_kodeOnderdilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_kodeOnderdilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_kodeOnderdilActionPerformed

    private void t_namaOnderdilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaOnderdilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaOnderdilActionPerformed

    private void t_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_hargaActionPerformed

    private void t_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jumlahActionPerformed
        Long harga, jumlah, subTotal;
        harga = Long.parseLong(t_harga.getText());
        jumlah = Long.parseLong(t_jumlah.getText());
        subTotal = harga * jumlah;
        t_subTotal.setText(Long.toString(subTotal));
        btn_add.requestFocus();
    }//GEN-LAST:event_t_jumlahActionPerformed

    private void btn_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierActionPerformed
        boolean closable = true;
        dialog_dataSupplier djb = new dialog_dataSupplier(null, closable);
        djb.setVisible(true);

        t_idSupplier.setText(djb.jo.getId_supplier());
        t_namaSupplier.setText(djb.jo.getToko_supplier());

        btn_onderdil.requestFocus();
        aktif();
    }//GEN-LAST:event_btn_supplierActionPerformed

    private void btn_onderdilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onderdilActionPerformed
        if (!t_idSupplier.getText().trim().isEmpty()) {
            // Blok kode yang akan dijalankan jika t_idSupplier tidak kosong
            boolean closable = true;
            dialog_dataOnderdil djb = new dialog_dataOnderdil(null, closable, t_idSupplier.getText());
            djb.setVisible(true);

            t_kodeOnderdil.setText(djb.jo.getKode_onderdil());
            t_namaOnderdil.setText(djb.jo.getNama_onderdil());
            t_harga.setText(String.valueOf(djb.jo.getHarga_onderdil()));

            t_jumlah.requestFocus();
        } else {
            // Blok kode yang akan dijalankan jika t_idSupplier kosong
            JOptionPane.showMessageDialog(null, "Pilih Supplier terlebih dahulu");
        }
        aktif();

    }//GEN-LAST:event_btn_onderdilActionPerformed

    private void t_subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_subTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_subTotalActionPerformed

    private void btn_perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perbaruiActionPerformed
        perbaruiSementara();
        total();
    }//GEN-LAST:event_btn_perbaruiActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if (validasiInput() == true) {
            DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
            tb.addRow(new Object[]{
                t_kodeOnderdil.getText(),
                t_namaOnderdil.getText(),
                t_harga.getText(),
                t_jumlah.getText(),
                t_subTotal.getText()      
            });
            JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan!");
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan!");
        }     
        total();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_hapusSementaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusSementaraActionPerformed
        int index = tbl_sementara.getSelectedRow();
        if (index != -1) {
        if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
            tb.removeRow(tbl_sementara.getSelectedRow());
        }
        }else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
        total();
    }//GEN-LAST:event_btn_hapusSementaraActionPerformed

    private void t_subTotalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_subTotalMouseMoved
        String x = t_jumlah.getText();
        if(!x.equals("")){
            int y = Integer.parseInt(x) * Integer.parseInt(t_harga.getText());
            t_subTotal.setText(String.valueOf(y));
        }else{
            t_subTotal.setText("");
        }
    }//GEN-LAST:event_t_subTotalMouseMoved

    private void tbl_sementaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sementaraMouseClicked
        int row = tbl_sementara.getSelectedRow();
        
        t_kodeOnderdil.setText(tbl_sementara.getModel().getValueAt(row, 0).toString());
        t_namaOnderdil.setText(tbl_sementara.getModel().getValueAt(row, 1).toString());
        t_harga.setText(tbl_sementara.getModel().getValueAt(row, 2).toString());
        t_jumlah.setText(tbl_sementara.getModel().getValueAt(row, 3).toString());
        t_subTotal.setText(tbl_sementara.getModel().getValueAt(row, 4).toString());
    }//GEN-LAST:event_tbl_sementaraMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btn_add;
    private rojerusan.RSMaterialButtonRectangle btn_batal;
    private rojerusan.RSMaterialButtonRectangle btn_batal1;
    private rojerusan.RSMaterialButtonRectangle btn_clear;
    private rojerusan.RSMaterialButtonRectangle btn_hapus;
    private rojerusan.RSMaterialButtonRectangle btn_hapusSementara;
    private javax.swing.JButton btn_onderdil;
    private rojerusan.RSMaterialButtonRectangle btn_perbarui;
    private javax.swing.JButton btn_supplier;
    private rojerusan.RSMaterialButtonRectangle btn_tambah;
    private rojerusan.RSMaterialButtonRectangle btn_tambah1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel judul3;
    private javax.swing.JLabel lb_total;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pn_detail;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin111;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin112;
    private scrollbarwin11.ScrollPaneWin11 scrollPaneWin113;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_idSupplier;
    private javax.swing.JTextField t_jumlah;
    private javax.swing.JTextField t_kodeOnderdil;
    private javax.swing.JTextField t_kodeSupply;
    private javax.swing.JTextField t_namaOnderdil;
    private javax.swing.JTextField t_namaSupplier;
    private javax.swing.JTextField t_pencarian;
    private javax.swing.JTextField t_subTotal;
    private javax.swing.JTextField t_tglSupply;
    private javax.swing.JPanel tambahData;
    private javax.swing.JPanel tampilData;
    private tablecustom.tablez tbl_data;
    private tablecustom.tablez tbl_detail;
    private tablecustom.tablez tbl_sementara;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        btn_hapus.setVisible(false);
        btn_batal.setVisible(false);
        pn_detail.setVisible(false);
        List<model_supply> list = servis.getData();
        tblModel.setData(list);
    }

    private void dataTabel() {
        tampilData.setVisible(false);
        tambahData.setVisible(true);

        int row = tbl_data.getSelectedRow();
        judul2.setText("Perbarui Data Supply");

        t_kodeSupply.setEnabled(false);
        t_tglSupply.setEnabled(false);
        t_idSupplier.setEnabled(false);
        t_namaSupplier.setEnabled(false);
        t_kodeOnderdil.setEnabled(false);
        t_namaOnderdil.setEnabled(false);
        t_harga.setEnabled(false);
        t_jumlah.setEnabled(true);
        t_subTotal.setEditable(false);

        t_kodeSupply.setText(tbl_data.getModel().getValueAt(row, 1).toString());
        t_tglSupply.setText(tbl_data.getModel().getValueAt(row, 2).toString());
        t_idSupplier.setText(tbl_data.getModel().getValueAt(row, 3).toString());
        t_namaSupplier.setText(tbl_data.getModel().getValueAt(row, 4).toString());
        t_kodeOnderdil.setText(tbl_data.getModel().getValueAt(row, 5).toString());
        t_namaOnderdil.setText(tbl_data.getModel().getValueAt(row, 6).toString());
        t_harga.setText(tbl_data.getModel().getValueAt(row, 7).toString());

        aktif();
        btn_tambah1.setText("PERBARUI");
        btn_clear.setText("BATAL");
        btn_batal1.setVisible(false);
        btn_batal.setVisible(true);

    }

    private void aktif() {
        t_jumlah.setEnabled(true);
    }

    private void tampilPanel() {
        mainPanel.removeAll();
        mainPanel.add(new supply());
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    private void resetForm() {
        btn_tambah.requestFocus();
        btn_tambah.setText("TAMBAH");
        t_kodeSupply.setText("");
        t_tglSupply.setText("");
        t_idSupplier.setText("");
        t_namaSupplier.setText("");
        t_kodeOnderdil.setText("");
        t_namaOnderdil.setText("");
        t_harga.setText("");
        t_jumlah.setText("");
        t_subTotal.setText("");

    }
    
    private void simpanData() {

        if (validasiIn() == true) {
            String kode = t_kodeSupply.getText();
            String tgl = t_tglSupply.getText();
            Long total = Long.valueOf(lb_total.getText());
            String sup = t_idSupplier.getText();

            model_supply sp = new model_supply();
            model_supplier spr = new model_supplier();

            sp.setKode_supply(kode);
            try {
                // Parse the string date to java.util.Date
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy"); // Replace "your_date_format" with the actual date format
                Date tgldate = sdf.parse(tgl);
                sp.setTgl_supply(tgldate); // Corrected line
            } catch (ParseException e) {
                e.printStackTrace(); // Handle the parsing exception appropriately
                return; // Return or handle error accordingly
            }
            sp.setTotal_supply(total);
            spr.setId_supplier(sup);
            sp.setStatus("Pending");

            sp.setSupplier(spr);

            tblModel.tambahData(sp);
            servis.tambahData(sp);
        }
        
    }
    
    private void simpatDet() {
        if (validasiIn()==true) {
            DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
            int rowCount = tb.getRowCount();

            for (int i = 0; i < rowCount; i++) {
                model_detailSupply d = new model_detailSupply();
                model_supply s = new model_supply();
                model_onderdil mod = new model_onderdil();

                String kode = t_kodeSupply.getText();
                String kodeOnderdil = tb.getValueAt(i, 0).toString();
                String namaOnderdil = tb.getValueAt(i, 1).toString();
                String harga = tb.getValueAt(i, 2).toString();
                String jumlah = tb.getValueAt(i, 3).toString();
                String subTotal = tb.getValueAt(i, 4).toString();

                s.setKode_supply(kode);
                mod.setKode_onderdil(kodeOnderdil);
                mod.setNama_onderdil(namaOnderdil);
                mod.setHarga_onderdil(Long.valueOf(harga));
                d.setJmh_supply(Integer.valueOf(jumlah));
                d.setSubtotal_detailsupply(Long.valueOf(subTotal));

                d.setOnderdil(mod);
                d.setSupply(s);
                
                servis_det.tambahData(d);
            }
            
        }
    }


    private void perbaruiData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            model_supply mod = tblModel.getData(tbl_data.convertRowIndexToModel(index));

            if (validasiInput() == true) {
                
                loadData();
                resetForm();
                tampilPanel();

            }
        }
    }
    
    private boolean validasiIn() {
        boolean valid = false;
        if (t_kodeSupply.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Supply Onderdil tidak boleh kosong");
        } else if (t_tglSupply.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tgl Supply tidak boleh kosong");
        } else if (lb_total.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harus Ada Onderdil Yang di Pesan");
        } else if (t_idSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Supplier tidak boleh kosong");
        
        } else {
            valid = true;
        }
        return valid;
    }
    
    private boolean validasiInput() {
        boolean valid = false;
        if (t_kodeSupply.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Supply Onderdil tidak boleh kosong");
        } else if (t_tglSupply.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tgl Supply tidak boleh kosong");
        } else if (t_idSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ID Supplier tidak boleh kosong");
        } else if (t_namaSupplier.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Toko Supplier tidak boleh kosong");
        } else if (t_kodeOnderdil.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Onderdil tidak boleh kosong");
        } else if (t_namaOnderdil.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Onderdil tidak boleh kosong");
        } else if (t_harga.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Harga Onderdil tidak boleh kosong");
        } else if (t_jumlah.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Jumlah Onderdil tidak boleh kosong");
        } else if (t_subTotal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "SubTotal tidak boleh kosong");
        } else {
            valid = true;
        }
        return valid;
    }

    private void hapusData() {
        int index = tbl_data.getSelectedRow();
        if (index != -1) {
            model_supply spl = tblModel.getData(tbl_data.convertRowIndexToModel(index));
            if (JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                servis.hapusData(spl);
                tblModel.hapusData(index);
                loadData();
                resetForm();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pilih dahulu record yang akan dihapus");
        }
    }

    private void pencarian() {
        List<model_supply> list = servis.pencarianData(t_pencarian.getText().toLowerCase());
        tblModel.setData(list);
    }

    private void setTanggal() {
        java.util.Date sekarang = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd-MM-yyyy");
        t_tglSupply.setText(kal.format(sekarang));
    }

    private void perbaruiSementara() {
        
        int selectedRowIndex = tbl_sementara.getSelectedRow();

        if (selectedRowIndex != -1) {
            DefaultTableModel tb = (DefaultTableModel) tbl_sementara.getModel();
            
            tb.setValueAt(t_kodeOnderdil.getText(), selectedRowIndex, 0);
            tb.setValueAt(t_namaOnderdil.getText(), selectedRowIndex, 1);
            tb.setValueAt(t_harga.getText(), selectedRowIndex, 2);
            tb.setValueAt(t_jumlah.getText(), selectedRowIndex, 3);
            tb.setValueAt(t_subTotal.getText(), selectedRowIndex, 4);

            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diupdate!");
        }

    }

    private void clear() {
        t_kodeOnderdil.setText("");
        t_namaOnderdil.setText("");
        t_harga.setText("");
        t_jumlah.setText("");
        t_subTotal.setText("");
    }

    private void total() {
        int columnCount = tbl_sementara.getRowCount();
        int total = 0;

            for(int i = 0; i < columnCount; i++){
                total += Integer.parseInt(tbl_sementara.getValueAt(i, 4).toString());
            }
            lb_total.setText(String.valueOf(total));
    }
   
}
